Repository taskord/taskord, pull requests merged in 2020-08, with the labels that each got.

#155 Add Tests
  app/Http/Livewire/Admin/Adminbar.php
  tests/Feature/AdminBarTest.php
  tests/Feature/AnswerTest.php
  tests/Feature/CommentTest.php
  tests/Feature/QuestionTest.php
  tests/Feature/TaskTest.php
Labels: testing

#176 Add Matrix CI Build
  .github/workflows/ci.yml
Labels: chore

#178 Update Contact URL
  resources/views/components/footer.blade.php
Labels: enhancement

#179 chore: `notification` -> `notifications`
  resources/views/livewire/notification/notifications.blade.php
Labels: chore
